-- Migration 016: rule packs for Australia, Canada, Brazil and South Korea (version 2026.10.1, in force from Oct 3, 2026).
-- Generated from src/proto/rulepacks.ts. Insert-only and idempotent: rerunning it changes nothing.
-- Statements are separated by lines containing only "-- ;" (see api/db/migrate.mjs).

insert into jurisdictions (code, name, iso3, comprehensive_sanctions, iso_numeric) values
  ('AU', 'Australia', 'AUS', null, '036'),
  ('CA', 'Canada', 'CAN', null, '124'),
  ('BR', 'Brazil', 'BRA', null, '076'),
  ('KR', 'South Korea', 'KOR', null, '410')
on conflict (code) do nothing
-- ;
insert into investor_classes (code, jurisdiction, label, stamp, rule_ref, source_id, threshold, requires_opt_in, opt_in_label) values
  ('AU_WHOLESALE', 'AU', 'Wholesale client', 'Wholesale client', 'Corporations Act s761G(7); regs 7.1.18, 7.1.28', 'au-reg-7128', 'Product value of at least A$500,000; or a qualified accountant''s certificate given within 2 years showing net assets of at least A$2.5M or gross income of at least A$250,000 in each of the last 2 financial years; or a business that is not a small business; or control by a wholesale client.', false, null),
  ('AU_PRO', 'AU', 'Professional investor', 'Professional investor', 'Corporations Act s9; s761G(7)(d)', 'au-wholesale-guide', 'AFS licensee, APRA-regulated body, large superannuation trustee or listed entity, or a person who has or controls gross assets of at least A$10M.', false, null),
  ('CA_AI', 'CA', 'Accredited investor', 'Accredited investor', 'NI 45-106 s1.1, s2.3', 'ca-ni45106', 'Individual: net financial assets over C$1M (with Form 45-106F9), or over C$5M; net income over C$200,000 (C$300,000 with a spouse) in each of the last two years; or net assets of at least C$5M. Non-individual: net assets of at least C$5M, listed institutions, or every owner an accredited investor.', false, null),
  ('CA_PC', 'CA', 'Permitted client', 'Permitted client', 'NI 31-103 s1.1', 'ca-ni31103', 'Individual with financial assets over C$5M; a person other than an individual or investment fund with net assets of at least C$25M; listed institutions.', false, null),
  ('CA_MIN', 'CA', 'Minimum amount purchaser', 'Minimum amount', 'NI 45-106 s2.10', 'ca-ni45106', 'Non-individual paying an acquisition cost of at least C$150,000 in cash at the time of the distribution, not created solely to use the exemption. Not available to individuals.', false, null),
  ('BR_QUAL', 'BR', 'Investidor qualificado', 'Qualified investor', 'Resolução CVM 30 art. 12', 'br-rcvm30', 'Financial investments over R$1,000,000.00 with a written attestation of qualified investor status; or an individual approved in a CVM-recognised exam or holding a CVM-approved certification; or a professional investor.', true, 'written attestation'),
  ('BR_PRO', 'BR', 'Investidor profissional', 'Professional investor', 'Resolução CVM 30 art. 11', 'br-rcvm30', 'Financial investments over R$10,000,000.00 with a written attestation; or a financial institution, insurer, pension entity, investment fund, authorised manager, or non-resident investor.', false, null),
  ('KR_PRO', 'KR', 'Professional investor', 'Professional investor', 'FSCMA Art. 9(5); Enforcement Decree Art. 10', 'kr-pro-2019', 'Individual: financial investment products of at least KRW 50 million held for a year, plus annual income of at least KRW 100 million (KRW 150 million with a spouse), net assets of at least KRW 500 million excluding the primary residence, or a financial profession qualification. Corporations: listed, regulated, or (unverified figure) KRW 10 billion in financial investment products.', false, null),
  ('KR_QPI', 'KR', 'Qualified professional investor', 'Qualified professional', 'FSCMA Art. 279; Enforcement Decree Art. 301', 'kr-decree-303', 'Financial institutions, pension funds, public funds and the other institutions named in Enforcement Decree Art. 301, to whom a foreign collective investment scheme may be privately placed under the simplified registration route.', false, null)
on conflict (code) do nothing
-- ;
insert into booking_centers (id, name, jurisdiction, licence, requires_class, rule_text, rule_ref, source_id, requires_any) values
  ('SYD', 'Sydney', 'AU', 'AFS licensee authorised for wholesale clients only (fictional licensee)', 'AU_WHOLESALE', 'Dealing from Australia in a scheme with no Product Disclosure Statement: wholesale clients or professional investors only.', 'Corporations Act s761G, s1012; s601ED(2)', 'au-s601ed', array['AU_WHOLESALE', 'AU_PRO']),
  ('TOR', 'Toronto', 'CA', 'Exempt market dealer registered in Ontario (fictional licensee)', 'CA_AI', 'Exempt market dealer distributing a foreign fund in Canada: accredited investors, permitted clients, or non-individuals under the C$150,000 minimum amount exemption.', 'NI 31-103 s7.1(2)(d); NI 45-106 s2.3, s2.10', 'ca-ni31103', array['CA_AI', 'CA_PC', 'CA_MIN']),
  ('SAO', 'São Paulo', 'BR', 'Distributor of securities authorised by the Central Bank and CVM (fictional licensee)', 'BR_QUAL', 'Placing a feeder for an offshore fund from Brazil: investidores qualificados with a written attestation, or investidores profissionais.', 'Resolução CVM 30 arts 11, 12; Resolução CVM 175', 'br-rcvm30', array['BR_QUAL', 'BR_PRO']),
  ('SEL', 'Seoul', 'KR', 'Investment broker licensed under the FSCMA (fictional licensee)', 'KR_PRO', 'Selling a privately placed foreign collective investment scheme from Korea: professional investors or qualified professional investors only.', 'FSCMA Art. 279; Enforcement Decree Arts 301, 303', 'kr-offshore-guide', array['KR_PRO', 'KR_QPI'])
on conflict (id) do nothing
-- ;
insert into rule_packs (id, version, jurisdiction, status, summary, effective_from, effective_to, approved_by) values
  ('AU/eligibility', '2026.10.1', 'AU', 'active', 'Wholesale clients (Corporations Act s761G(7): A$500,000 product value, certified A$2.5M net assets or A$250,000 gross income, large business) and professional investors (s9: A$10M gross assets); foreign schemes offered without a PDS to wholesale clients only (s601ED(2)); ASIC foreign financial services provider relief to 31 March 2027.', '2026-10-03'::date, null::date, 'pending counsel review'),
  ('CA/eligibility', '2026.10.1', 'CA', 'active', 'Accredited investors (NI 45-106 s1.1: C$1M financial assets with Form 45-106F9, C$5M financial assets, C$200,000 or C$300,000 income, C$5M net assets; non-individuals C$5M net assets), permitted clients (NI 31-103: C$5M financial assets, C$25M net assets), minimum amount C$150,000 for non-individuals (s2.10); international dealer exemption for permitted clients (s8.18).', '2026-10-03'::date, null::date, 'pending counsel review'),
  ('BR/eligibility', '2026.10.1', 'BR', 'active', 'Investidor qualificado (Resolução CVM 30 art. 12: financial investments over R$1 million with written attestation, or CVM certification) and investidor profissional (art. 11: over R$10 million, institutions, non-residents); offshore funds reached through Resolução CVM 175 feeder classes that may invest fully abroad.', '2026-10-03'::date, null::date, 'pending counsel review'),
  ('KR/eligibility', '2026.10.1', 'KR', 'active', 'Professional investors (FSCMA Art. 9(5); Enforcement Decree Art. 10: KRW 50 million in financial investment products for a year plus KRW 100 million income, KRW 150 million with a spouse, KRW 500 million net assets or a professional qualification) and qualified professional investors (Enforcement Decree Art. 301); foreign collective investment schemes registered with the FSC before sale (Art. 279), privately placed to professional investors through a licensed distributor.', '2026-10-03'::date, null::date, 'pending counsel review')
on conflict (id, version) do nothing
